# -----------------------------------------------------------------------------
# Site Settings
# -----------------------------------------------------------------------------

name: Christopher Schymura
email: christopher [dot] schymura [at] posteo [dot] de
description: Personal website of Christopher Schymura.
footer_text: >
  <br /> This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>. Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.

# last_updated: true

url: chrschy.de

# -----------------------------------------------------------------------------
# Social Integration
# -----------------------------------------------------------------------------
github_username: chrschy
twitter_username:
linkedin_username: cschymura
scholar_userid: _4-LU5UAAAAJ&hl
orcid_id: 0000-0002-6128-3556
research_gate_profile: Christopher_Schymura
contact_note: Feel free to drop me a line via email.

google_analytics: 

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: page
    output: true
    permalink: /news/:path/
  talks:
    defaults:
      layout: page
    output: true
    permalink: /talks/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 10

# -----------------------------------------------------------------------------
# Jekyll Settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
# highlighter: pygments

# Include/Exclude
include: ['_pages']
exclude: [node_modules]

# Plugins
plugins:
  - jekyll-paginate
  - jekyll/scholar
  - jemoji

# Jekyll-Scholar
scholar:
  last_name: Schymura
  style: apa
  locale: en
  sort_by: year
  order: descending
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: publication
  reference_tagname: div

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------

jquery_version: "1.12.4"
katex_version: "0.7.1"
anchorjs_version: "3.2.2"
